name: Create Azure VM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create Resource Group
      run: |
        az group create --name myResourceGroup --location eastus

    - name: Create Virtual Machine
      run: |
        az vm create \
          --resource-group myResourceGroup \
          --name myVM \
          --image UbuntuLTS \
          --admin-username azureuser \
          --generate-ssh-keys