name: Create Azure VM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create Resource Group
      run: |
        az group create --name MyResourceGroup --location CanadaCentral

    - name: Create a Virtual Network
      run: |
        az network vnet create --resource-group MyResourceGroup --name Vnet1 --subnet-name Subnet1

    - name: Create a publica IP
      run: |
        az network public-ip create --resource-group MyResourceGroup --name MyPublicIP1

    - name: Create a NSG
      run: |
        az network nsg create --resource-group MyResourceGroup --name MyNSG1

    - name: Create a NIC
      run: |
        az network nic create --resource-group MyResourceGroup --name NIC1 --subnet Subnet1 --vnet-name Vnet1 --public-ip-address MyPublicIP1
   
    - name: Create VM
      run: |
        az vm create \
        --resource-group MyResourceGroup \
        --name NewVM --image Ubuntu2204 \
        --admin-username azureuser \
        --admin-password MyPassword123 \
        --nics NIC1 \
        --size Standard_B1s \
        --license-type None
   